#!/bin/bash

#############
# hooks/build
#############

echo "[***********************]"
echo "[***] Build hook running "
echo "[***********************]"

docker build \
            --build-arg VERSION=$(git describe --tags --always) \
            --build-arg COMMIT=$(git rev-parse HEAD) \
            --build-arg URL=$(git config --get remote.origin.url) \
            --build-arg BRANCH=$(git rev-parse --abbrev-ref HEAD) \
            --build-arg DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
            --build-arg VCS_REF=`git rev-parse --short HEAD` \
            -t $IMAGE_NAME .